version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    ignore:
      - dependency-name: dependency-check
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly