providers:
  - airtap-sauce

browsers:
  - name: chrome
  - name: firefox
  # https://github.com/airtap/sauce/issues/11
  # - name: safari
  #   version: 12..latest
  - name: ios_saf
    version: 12..latest
  # TODO: look into android 10 failure
  - name: chrome for android
    version: 6..9
  - name: chrome for android
    version: 11
  - name: msedge

presets:
  local:
    providers:
      - airtap-playwright
    browsers:
      - name: chromium
      - name: firefox
