providers:
  - airtap-sauce

browsers:
  - name: chrome
  - name: ie
  - name: firefox
  - name: iphone
    version: '10.3'
  - name: android
    version: '6.0'
  - name: edge

presets:
  local:
    providers:
      - airtap-playwright
    browsers:
      - name: chromium
      - name: firefox
